/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appFrames;

import databaseConnection.MySQLConnection;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modeli.Polaznik;
import modeli.PolaznikFactory;

/**
 *
 * @author Nikola
 */
public class polazniciMenu extends javax.swing.JFrame {
    
       
    private String username;
    String fileName =  null;
    byte[] person_image = null;
    
    String grupaG= "";
    
        
    public void setUsername(String username) {
        this.username = username;
        prikazi_sliku();
    }
    public polazniciMenu() {
       
        initComponents();
    }
    
    public void polaznicitabela(){
        
        
  try {
        String query = "SELECT grupa, trener, vrsta_treninga, date FROM polaznici WHERE username = ?";
        Connection conn = MySQLConnection.getInstance().getConnection();
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, username);

        
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTablePolaznik.getModel();
       
        while (rs.next()) {
            Object[] row = new Object[4];
            row[0] = rs.getString("grupa");
            row[1] = rs.getString("trener");
            row[2] = rs.getString("vrsta_treninga");
            row[3] = rs.getString("date");
            model.addRow(row);
        }

        rs.close();
        pst.close();
        conn.close();

    } catch (SQLException ex) {
        System.out.println("Error: " + ex.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jComboVrstaTreninga = new javax.swing.JComboBox<>();
        jTextFieldTrener = new javax.swing.JTextField();
        jButtonChangeImage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelProfilna = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePolaznik = new javax.swing.JTable();
        jRadioindividualni = new javax.swing.JRadioButton();
        jRadiogrupni = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jButtonSave.setBackground(new java.awt.Color(102, 102, 102));
        jButtonSave.setText("Sacuvaj izmene");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jComboVrstaTreninga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Crossfit", "Yoga", "Kardio", "BodyBuilding", "Kruzni" }));

        jButtonChangeImage.setText("Promeni profilnu");
        jButtonChangeImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeImageActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cfk-district-logo.png"))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Grupa:");
        jTextField1.setBorder(null);

        jTextField2.setBackground(new java.awt.Color(0, 0, 102));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Vrsta treninga:");
        jTextField2.setBorder(null);

        jTextField3.setBackground(new java.awt.Color(0, 0, 102));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Trener:");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTablePolaznik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupa", "Trener", "Vrsta treninga", "Datum polazka"
            }
        ));
        jScrollPane1.setViewportView(jTablePolaznik);

        buttonGroup1.add(jRadioindividualni);
        jRadioindividualni.setForeground(new java.awt.Color(255, 255, 255));
        jRadioindividualni.setText("Individualni");
        jRadioindividualni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioindividualniActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadiogrupni);
        jRadiogrupni.setForeground(new java.awt.Color(255, 255, 255));
        jRadiogrupni.setText("Grupni");
        jRadiogrupni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadiogrupniActionPerformed(evt);
            }
        });

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioindividualni)
                                    .addComponent(jRadiogrupni))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProfilna, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel1)
                                .addGap(23, 23, 23))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(408, 408, 408)
                                        .addComponent(jButtonChangeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboVrstaTreninga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(298, 298, 298))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioindividualni)
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))))
                        .addComponent(jRadiogrupni))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelProfilna, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jButtonChangeImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboVrstaTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jButtonSave)
                                .addGap(172, 172, 172))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try{ 
            Connection conn = MySQLConnection.getInstance().getConnection();
            PreparedStatement stmt = null;
              String query = "UPDATE polaznici SET grupa = ?, vrsta_treninga = ?, trener = ? WHERE username = ?";  
              stmt = conn.prepareStatement(query);
              
                if (jRadiogrupni.isSelected()){
             grupaG= "grupni";
        }
                if (jRadioindividualni.isSelected()){
             grupaG = "individualni";
                }
                
                stmt.setString(1, grupaG);
                stmt.setString(2, jComboVrstaTreninga.getSelectedItem().toString());
                stmt.setString(3, jTextFieldTrener.getText());
                stmt.setString(4, username);
                stmt.executeUpdate();
            
            
             JOptionPane.showMessageDialog(null,"Uspesno ste izmenili podatke");
            
            
            }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }  
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioindividualniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioindividualniActionPerformed
         jRadioindividualni.isSelected();
         jTextFieldTrener.setText("Djordje Stojkovic");
    }//GEN-LAST:event_jRadioindividualniActionPerformed

    private void jRadiogrupniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadiogrupniActionPerformed
        jRadiogrupni.isSelected();
        jTextFieldTrener.setText("Zarko Vidovic");
    }//GEN-LAST:event_jRadiogrupniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       polazniciLP plp = new polazniciLP();
       plp.setVisible(true);
     setVisible(false);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonChangeImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeImageActionPerformed
        
    JFileChooser fileChooser = new JFileChooser();
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        
        try {
            byte[] imageData = Files.readAllBytes(selectedFile.toPath());
            
            String sql = "UPDATE images SET image_data = ? WHERE username = ?";
            Connection conn = MySQLConnection.getInstance().getConnection();
            PreparedStatement pst3 = conn.prepareStatement(sql);
            pst3.setBytes(1, imageData);
            pst3.setString(2, username); 
            int rowsUpdated = pst3.executeUpdate();
            
            if (rowsUpdated > 0) {
                ImageIcon imageIcon = new ImageIcon(imageData);
                Image image = imageIcon.getImage();
                Image scaledImage = image.getScaledInstance(jLabelProfilna.getWidth(), jLabelProfilna.getHeight(), Image.SCALE_SMOOTH);
                jLabelProfilna.setIcon(new ImageIcon(scaledImage));
                JOptionPane.showMessageDialog(this, "Profile image updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update profile image.");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred while updating profile image.");
        }
    }

    }//GEN-LAST:event_jButtonChangeImageActionPerformed

    /**
     * @param args the command line arguments
     */
  //  public static void main(String args[]) {
     //  /* Set the Nimbus look and feel */
      //  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       // /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        // * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        // */
       // try {
         //   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
          //      if ("Nimbus".equals(info.getName())) {
             //       javax.swing.UIManager.setLookAndFeel(info.getClassName());
             //       break;
             //   }
          //  }
     //   } catch (ClassNotFoundException ex) {
       //     java.util.logging.Logger.getLogger(polazniciMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // } catch (InstantiationException ex) {
       //     java.util.logging.Logger.getLogger(polazniciMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       // } catch (IllegalAccessException ex) {
        //    java.util.logging.Logger.getLogger(polazniciMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      //  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //    java.util.logging.Logger.getLogger(polazniciMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      //  }
        //</editor-fold>

      //  /* Create and display the form */
      //  java.awt.EventQueue.invokeLater(new Runnable() {
       //     public void run() {
         //       new polazniciMenu().setVisible(true);
         //   }
      //  });
  //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonChangeImage;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboVrstaTreninga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelProfilna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadiogrupni;
    private javax.swing.JRadioButton jRadioindividualni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePolaznik;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldTrener;
    // End of variables declaration//GEN-END:variables

 private void prikazi_sliku() {
        try{
          
            Connection conn = MySQLConnection.getInstance().getConnection();
            String query1 = "SELECT images FROM polaznici WHERE username = '" + username + "'";
            PreparedStatement pst2 = conn.prepareStatement(query1);
            ResultSet rs = pst2.executeQuery(query1);
            
            byte[] person_image =  null; 
            
            if (rs.next()) {
     
            byte[] imageData = rs.getBytes("images");
    
    
                ImageIcon imageIcon = new ImageIcon(imageData);
                Image image = imageIcon.getImage();
  
                Image scaledImage = image.getScaledInstance(jLabelProfilna.getWidth(), jLabelProfilna.getHeight(), Image.SCALE_SMOOTH);
   
                 jLabelProfilna.setIcon(new ImageIcon(scaledImage));
            }
         
          }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
                  }
        }
 }