/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appFrames;



/**
 *
 * @author Nikola
 */
public class start extends javax.swing.JFrame {
  

    /**
     * Creates new form Start
     */
    public start() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbackgroundPanel = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        jOpcija = new javax.swing.JLabel();
        jButtonTrener = new javax.swing.JButton();
        jButtonPolaznik = new javax.swing.JButton();
        jwelcome = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbackgroundPanel.setBackground(new java.awt.Color(0, 0, 102));

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cfk-district-logo.png"))); // NOI18N

        jOpcija.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jOpcija.setForeground(new java.awt.Color(255, 255, 255));
        jOpcija.setText("Izaberite opciju:");

        jButtonTrener.setBackground(new java.awt.Color(0, 0, 51));
        jButtonTrener.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTrener.setText("Trener");
        jButtonTrener.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTrener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrenerActionPerformed(evt);
            }
        });

        jButtonPolaznik.setBackground(new java.awt.Color(0, 0, 51));
        jButtonPolaznik.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPolaznik.setText("Polaznik");
        jButtonPolaznik.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPolaznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPolaznikActionPerformed(evt);
            }
        });

        jwelcome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jwelcome.setForeground(new java.awt.Color(255, 255, 255));
        jwelcome.setText("Centar Fizicke Kulture District");

        jTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jTextField1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Dobrodosli");
        jTextField1.setBorder(null);

        javax.swing.GroupLayout jbackgroundPanelLayout = new javax.swing.GroupLayout(jbackgroundPanel);
        jbackgroundPanel.setLayout(jbackgroundPanelLayout);
        jbackgroundPanelLayout.setHorizontalGroup(
            jbackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundPanelLayout.createSequentialGroup()
                .addGroup(jbackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbackgroundPanelLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jwelcome))
                    .addGroup(jbackgroundPanelLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addGroup(jbackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLogo)))
                    .addGroup(jbackgroundPanelLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jOpcija))
                    .addGroup(jbackgroundPanelLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(jbackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jbackgroundPanelLayout.setVerticalGroup(
            jbackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLogo)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jwelcome)
                .addGap(30, 30, 30)
                .addComponent(jOpcija)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButtonTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButtonPolaznik, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPolaznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPolaznikActionPerformed
        polazniciLP plp = new polazniciLP();
        plp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonPolaznikActionPerformed

    private void jButtonTrenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrenerActionPerformed
     trenerLogin tli = new trenerLogin();
     tli.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonTrenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPolaznik;
    private javax.swing.JButton jButtonTrener;
    private javax.swing.JLabel jLogo;
    private javax.swing.JLabel jOpcija;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jbackgroundPanel;
    private javax.swing.JLabel jwelcome;
    // End of variables declaration//GEN-END:variables
}
