/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appFrames;

import appFrames.trenerMenu.RandomNumberGeneratorThread;
import com.toedter.calendar.JCalendar;
import databaseConnection.MySQLConnection;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.io.File;
import java.awt.image.BufferedImage;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import modeli.PolaznikFactory;
import modeli.PolaznikFactoryImpl;


/**
 *
 * @author Nikola
 */
public class trenerMenu extends javax.swing.JFrame {
    
    String pol = "";
    String grupa = "";
    String trener = "";
    byte[] person_image = null;
    String grupaG = "";
    private String username = "djordjeS";
    
    /**
     * Creates new form trenerMenu
     */
    public trenerMenu() {
        initComponents();
        
    }
     private void grupioriindividualni(){
        
         
        if (jRadioGrupni.isSelected()){
             grupaG= "grupni_polaznici";
        }
     if (jRadioIndividualni.isSelected()){
             grupaG = "individualni_polaznici";
     }
        try{
             String query = "SELECT * FROM "  + grupaG ;
             Connection conn = MySQLConnection.getInstance().getConnection();
              PreparedStatement pst = conn.prepareStatement(query);
               ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTablePolaznici.getModel();
            model.setRowCount(0);
             while (rs.next()) {
             Object[] row = new Object[9]; 
             row[0] = rs.getInt("Id");
             row[1] = rs.getString("ime");
             row[2] = rs.getString("prezime");
             row[3] = rs.getString("pol");
             row[4] = rs.getString("broj_telefona");
             row[5] = rs.getString("grupa");
             row[6] = rs.getString("vrsta_treninga");
             row[7] = rs.getString("trener");
             row[8] = rs.getString("date");
             model.addRow(row);
            
    }
    
    rs.close();
    conn.close();
} catch (Exception ex) {
            System.out.println("Greska" + ex.getLocalizedMessage());
}
     }            
              

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePolaznici = new javax.swing.JTable();
        jLabelSlikaTrenera = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioGrupni = new javax.swing.JRadioButton();
        jRadioIndividualni = new javax.swing.JRadioButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jRadioButtonMuski = new javax.swing.JRadioButton();
        jRadioButtonZenski = new javax.swing.JRadioButton();
        jTextFieldTelefon = new javax.swing.JTextField();
        jRadioButtonGrupni = new javax.swing.JRadioButton();
        jRadioButtonIndividualni = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextFieldTrener = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonDodaj = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLaberSlikaTrenera = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cfk-district-logo.png"))); // NOI18N

        jTablePolaznici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ime", "Prezime", "Pol", "Broj telefona", "Grupa", "Vrsta treninga", "Trener", "Datum polazka"
            }
        ));
        jScrollPane1.setViewportView(jTablePolaznici);

        jTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Izaberi grupu:");
        jTextField1.setBorder(null);

        buttonGroup1.add(jRadioGrupni);
        jRadioGrupni.setForeground(new java.awt.Color(255, 255, 255));
        jRadioGrupni.setText("Grupni");
        jRadioGrupni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioGrupniActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioIndividualni);
        jRadioIndividualni.setForeground(new java.awt.Color(255, 255, 255));
        jRadioIndividualni.setText("Individualni");
        jRadioIndividualni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioIndividualniActionPerformed(evt);
            }
        });

        jTextField10.setBackground(new java.awt.Color(0, 0, 102));
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("Ime");
        jTextField10.setBorder(null);

        jTextField11.setBackground(new java.awt.Color(0, 0, 102));
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setText("Prezime");
        jTextField11.setBorder(null);

        jTextField12.setBackground(new java.awt.Color(0, 0, 102));
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("Broj telefona");
        jTextField12.setBorder(null);

        jTextField13.setBackground(new java.awt.Color(0, 0, 102));
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setText("Pol");
        jTextField13.setBorder(null);

        jTextField14.setBackground(new java.awt.Color(0, 0, 102));
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setText("Vrsta treninga");
        jTextField14.setBorder(null);

        jTextField15.setBackground(new java.awt.Color(0, 0, 102));
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setText("Grupa");
        jTextField15.setBorder(null);

        jTextField16.setBackground(new java.awt.Color(0, 0, 102));
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setText("Trener");
        jTextField16.setBorder(null);

        buttonGroup2.add(jRadioButtonMuski);
        jRadioButtonMuski.setText("Muski");

        buttonGroup2.add(jRadioButtonZenski);
        jRadioButtonZenski.setText("Zenski");

        buttonGroup3.add(jRadioButtonGrupni);
        jRadioButtonGrupni.setText("Grupni");
        jRadioButtonGrupni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGrupniActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButtonIndividualni);
        jRadioButtonIndividualni.setText("Individualni");
        jRadioButtonIndividualni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIndividualniActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Crossfit", "Yoga", "Kardio", "BodyBuilding", "Kruzni" }));

        jButtonSave.setText("Sacuvaj izmene");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Obrisi");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(0, 0, 102));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Datum polazka:");
        jTextField3.setBorder(null);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLaberSlikaTrenera, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioIndividualni)
                                            .addComponent(jRadioGrupni))))
                                .addGap(77, 77, 77)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jButtonDodaj)
                                .addGap(89, 89, 89)
                                .addComponent(jButtonDelete)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(79, 79, 79))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jButtonSave)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton1))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jRadioButtonZenski)
                                                                .addComponent(jRadioButtonMuski))
                                                            .addGap(81, 81, 81)
                                                            .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(49, 49, 49)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButtonGrupni)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(20, 20, 20)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jRadioButtonIndividualni)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(301, 301, 301)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSlikaTrenera)
                                .addGap(123, 123, 123))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabelSlikaTrenera)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonGrupni)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonIndividualni))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonMuski, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonZenski)))))
                                .addGap(98, 123, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLaberSlikaTrenera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioGrupni)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioIndividualni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonDodaj)
                            .addComponent(jButtonSave)
                            .addComponent(jButton1))))
                .addGap(83, 83, 83)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try{     
            
            int row = jTablePolaznici.getSelectedRow();
            String value = (jTablePolaznici.getModel().getValueAt(row,0).toString());
            
            Connection conn = MySQLConnection.getInstance().getConnection();
            PreparedStatement stmt = null;
            
            String query = "UPDATE polaznici SET ime = ?,prezime = ?,pol = ?,broj_telefona = ?,grupa = ? ,vrsta_treninga = ?,trener = ?,images = ?"
                        + " WHERE id =" + value;
            stmt = conn.prepareStatement(query);
            
            stmt.setString(1, jTextFieldIme.getText());
            stmt.setString(2, jTextFieldPrezime.getText());
            String pol = "";
            
            if (jRadioButtonMuski.isSelected()){
                pol = "Muski";
            }
            if (jRadioButtonZenski.isSelected()){
                pol = "Zenski";
            }
            stmt.setString(3, pol);
            stmt.setString(4, jTextFieldTelefon.getText());
            String grupa = "";
            
            if (jRadioButtonGrupni.isSelected()){
                grupa = "grupni";
            }
            if (jRadioButtonIndividualni.isSelected()){
                grupa = "individualni";
            }
            stmt.setString(5, grupa);
            stmt.setString(6, jComboBox1.getSelectedItem().toString());
            stmt.setString(7, jTextFieldTrener.getText());
            stmt.setBytes(8, person_image);
            
            stmt.executeUpdate();
            
             JOptionPane.showMessageDialog(null,"Uspesno ste izmenili podatke");
            
            
             }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
                                                 
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jRadioButtonGrupniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGrupniActionPerformed
       jTextFieldTrener.setText("Zarko Vidovic");
    }//GEN-LAST:event_jRadioButtonGrupniActionPerformed

    private void jRadioButtonIndividualniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIndividualniActionPerformed
       jTextFieldTrener.setText("Djordje Stojkovic");
    }//GEN-LAST:event_jRadioButtonIndividualniActionPerformed

    private void jRadioGrupniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioGrupniActionPerformed
   grupioriindividualni();        
   
    }//GEN-LAST:event_jRadioGrupniActionPerformed

    private void jRadioIndividualniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioIndividualniActionPerformed
       grupioriindividualni();
    }//GEN-LAST:event_jRadioIndividualniActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
      try{
          Connection conn = MySQLConnection.getInstance().getConnection();
          PreparedStatement stmt = null;
          
          String query = "INSERT INTO polaznici (ime,prezime,pol,broj_telefona,grupa,trener,vrsta_treninga,images,username,password,date)VALUES(?,?,?,?,?,?,?,?,?,?,?)";        
          stmt = conn.prepareStatement(query);
          
         if (jRadioButtonMuski.isSelected()){
                pol = "Muski";
         }
         if (jRadioButtonZenski.isSelected()){
                pol = "Zenski";
         }
          
          if (jRadioButtonIndividualni.isSelected()){
                   grupa = "individualni";
          }
           if (jRadioButtonGrupni.isSelected()){
                   grupa = "grupni";   
           }
          
             RandomNumberGeneratorThread thread = new RandomNumberGeneratorThread(100);
             thread.start();
             thread.join();
             int randomNumber = thread.getRandomNumber();
             toString();
             
             stmt.setString(1, jTextFieldIme.getText());
             stmt.setString(2, jTextFieldPrezime.getText());
             stmt.setString(3, pol);
             stmt.setString(4, jTextFieldTelefon.getText());
             stmt.setString(5, grupa);
             stmt.setString(6, jTextFieldTrener.getText());
             stmt.setString(7, jComboBox1.getSelectedItem().toString());
             stmt.setBytes(8, person_image);
             stmt.setString(9, jTextFieldIme.getText()+ randomNumber);
             stmt.setString(10, jTextFieldIme.getText()+ randomNumber);
             
             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
             String date = sdf.format(jDateChooser1.getDate());
             stmt.setString(11, date);
             stmt.executeUpdate();
             
             
         JOptionPane.showMessageDialog(null, "You added new polaznik!");
            }catch(Exception e){
            System.out.println("Greska" + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
    int delete = JOptionPane.showConfirmDialog(null, "Da li ste sigurni da zelite da obrisete?", "Delete",JOptionPane.YES_NO_OPTION);
        if(delete==0){  
             try{
            int row = jTablePolaznici.getSelectedRow();
            String value = (jTablePolaznici.getModel().getValueAt(row,0).toString());
            
            Connection conn = MySQLConnection.getInstance().getConnection();
            PreparedStatement stmt = null;
            String query="DELETE FROM polaznici WHERE id =" + value;
            stmt = conn.prepareStatement(query);
            
            
            
            stmt.executeUpdate();
            
            
          JOptionPane.showMessageDialog(null,"Korisnik je uspesno obrisan");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
        }
            
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        buttonGroup2.clearSelection();
        jTextFieldTelefon.setText("");
        buttonGroup3.clearSelection();
        jComboBox1.setSelectedIndex(0);
        jTextFieldTrener.setText("");
        jDateChooser1.setDate(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        trenerLogin tlg = new trenerLogin();
        tlg.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
  //   * @param args the command line arguments
  //   */
  //  public static void main(String args[]) {
   //     /* Set the Nimbus look and feel */
    //    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
     //   /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     //    * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     //   try {
        //    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
         //       if ("Nimbus".equals(info.getName())) {
         //           javax.swing.UIManager.setLookAndFeel(info.getClassName());
           //         break;
          //      }
       //     }
     //   } catch (ClassNotFoundException ex) {
     //       java.util.logging.Logger.getLogger(trenerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      //      java.util.logging.Logger.getLogger(trenerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     //   } catch (IllegalAccessException ex) {
      //      java.util.logging.Logger.getLogger(trenerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     //   } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     //      java.util.logging.Logger.getLogger(trenerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     //   }
      // / //</editor-fold>

     //   /* Create and display the form */
     //   java.awt.EventQueue.invokeLater(new Runnable() {
      //      public void run() {
        //        new trenerMenu().setVisible(true);
      //      }
     //   });
  //  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSlikaTrenera;
    private javax.swing.JLabel jLaberSlikaTrenera;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonGrupni;
    private javax.swing.JRadioButton jRadioButtonIndividualni;
    private javax.swing.JRadioButton jRadioButtonMuski;
    private javax.swing.JRadioButton jRadioButtonZenski;
    private javax.swing.JRadioButton jRadioGrupni;
    private javax.swing.JRadioButton jRadioIndividualni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePolaznici;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldTelefon;
    private javax.swing.JTextField jTextFieldTrener;
    // End of variables declaration//GEN-END:variables

public class RandomNumberGeneratorThread extends Thread {
    private final Random random = new Random();
    private final int maxNumber;
    private int randomNumber;

    public RandomNumberGeneratorThread(int maxNumber) {
        this.maxNumber = maxNumber;
    }

    @Override
    public void run() {
        randomNumber = random.nextInt(maxNumber);
    }

    public int getRandomNumber() {
        return randomNumber;
    }
}
}






